- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Cog
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Saltern
  - Packed
<<<<<<< HEAD
  #- Reach
  #- Train
=======
  - Reach
  - Train
>>>>>>> af09e9315514441bd8e621c1c5f321d40e944aa8
